apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sql-backup-to-azure
  labels:
    app: sql-backup
spec:
  schedule: '0 0 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sql-backup-azure
              image:  producthouseacr.azurecr.io/cwc/auto-mysql-bak:latest
              env:
                - name: sql_host
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: host
                - name: sql_user
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: user
                - name: sql_password
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: password
                - name: azure_account
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: account
                - name: azure_accountKey
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: accountKey
                - name: azure_container
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: container

          restartPolicy: Never
      backoffLimit: 4
